# file: examples/workflows/pr-labeler-example.yml
# version: 1.0.0
# guid: c3d4e5f6-a7b8-49c0-d1e2-f3a4b5c6d7e8

# Example: Pull Request Labeler Workflow
# This is an example of how to set up automatic PR labeling in your repository
# Copy this to .github/workflows/pr-labeler.yml in your repository

name: Pull Request Labeler

# Automatically label pull requests based on changed files and branch names
on:
  pull_request_target:
    types: [opened, synchronize, reopened, edited]

jobs:
  labeler:
    # For repositories in the jdfalk organization, use the reusable workflow
    uses: jdfalk/ghcommon/.github/workflows/reusable-labeler.yml@main
    with:
      configuration-path: ".github/labeler.yml"
      sync-labels: true
      dot: true

    # Alternative: Self-contained version (if you don't want to use the reusable workflow)
    # Uncomment the following and comment out the "uses" block above:
    #
    # runs-on: ubuntu-latest
    # permissions:
    #   contents: read
    #   pull-requests: write
    # steps:
    #   - name: Checkout repository
    #     uses: actions/checkout@v4
    #     with:
    #       fetch-depth: 0
    #
    #   - name: Apply labels to pull request
    #     uses: actions/labeler@v5
    #     with:
    #       repo-token: ${{ github.token }}
    #       configuration-path: ".github/labeler.yml"
    #       sync-labels: true
    #       dot: true
