# file: examples/workflows/super-linter-improved-example.yml
# version: 1.0.0
# guid: 123e4567-e89b-12d3-a456-426614174000

name: Super Linter - Improved Example

on:
  pull_request:
    branches: [main, master]
  workflow_dispatch:
    inputs:
      show-details:
        description: "Show detailed processing info (for debugging)"
        required: false
        default: false
        type: boolean

permissions:
  contents: write
  pull-requests: write
  packages: read
  id-token: write

jobs:
  # Example 1: Standard configuration - concise output, issues only
  standard-linting:
    name: Standard Linting (Concise)
    uses: jdfalk/ghcommon/.github/workflows/reusable-super-linter.yml@main
    with:
      validate-all-codebase: false
      enable-auto-fix: true
      auto-commit-fixes: true
      show-detailed-summary: false # Default: concise, actionable output
      run-python: true
      run-shell: true
      run-go: true
      run-markdown: true
      run-yaml: true
      run-json: true
      run-github-actions: true
    secrets:
      github-token: ${{ secrets.GITHUB_TOKEN }}

  # Example 2: Debugging configuration - detailed output for troubleshooting
  debug-linting:
    name: Debug Linting (Detailed)
    if: github.event.inputs.show-details == 'true'
    uses: jdfalk/ghcommon/.github/workflows/reusable-super-linter.yml@main
    with:
      validate-all-codebase: true
      enable-auto-fix: false
      auto-commit-fixes: false
      show-detailed-summary: true # Verbose output for debugging
      run-python: true
      run-shell: true
      run-go: true
      run-markdown: true
      run-yaml: true
      run-json: true
      run-github-actions: true
    secrets:
      github-token: ${{ secrets.GITHUB_TOKEN }}

  # Example 3: Production configuration - auto-fix with concise summary
  production-linting:
    name: Production Linting
    if: github.ref == 'refs/heads/main'
    uses: jdfalk/ghcommon/.github/workflows/reusable-super-linter.yml@main
    with:
      validate-all-codebase: true
      enable-auto-fix: true
      auto-commit-fixes: true
      show-detailed-summary: false # Clean, focused output
      commit-message: "style: auto-fix code formatting [skip ci]"
      run-security: true
    secrets:
      github-token: ${{ secrets.GITHUB_TOKEN }}
