# file: examples/workflows/unified-automation-with-intelligent-labeling.yml
# version: 1.0.0
# guid: 0a1b2c3d-4e5f-6a7b-8c9d-0e1f2a3b4c5d

name: Enhanced Unified Automation with Intelligent Labeling

on:
  # Run on issue events for real-time labeling
  issues:
    types: [opened, edited, reopened]
  
  # Run on schedule for batch processing
  schedule:
    - cron: "0 2 * * *"  # Daily at 2 AM UTC
  
  # Manual trigger
  workflow_dispatch:
    inputs:
      operation:
        description: "Which operation to run"
        required: false
        default: "all"
        type: choice
        options:
          - all
          - intelligent-labeling
          - issues
          - docs
          - label
          - lint
          - rebase
      dry_run:
        description: "Run in dry-run mode"
        required: false
        default: false
        type: boolean

permissions:
  contents: write
  issues: write
  pull-requests: write
  security-events: read
  repository-projects: write
  actions: write
  checks: write
  statuses: write

jobs:
  unified-automation:
    uses: jdfalk/ghcommon/.github/workflows/reusable-unified-automation.yml@main
    with:
      # Main operation control
      operation: ${{ inputs.operation || 'all' }}
      
      # Issue Management Configuration
      im_operations: "auto"
      im_dry_run: ${{ inputs.dry_run || false }}
      im_force_update: false
      im_cleanup_issue_updates: true
      
      # Documentation Updates
      docs_dry_run: ${{ inputs.dry_run || false }}
      docs_create_pr: true
      docs_auto_merge: false
      docs_continue_on_error: true
      
      # PR Labeling
      labeler_sync_labels: true
      labeler_dot: true
      
      # Intelligent Issue Labeling Configuration
      il_enabled: true
      il_dry_run: ${{ inputs.dry_run || false }}
      il_batch_size: 15
      il_use_ai_fallback: true
      il_confidence_threshold: 0.7
      il_max_labels_per_issue: 8
      il_preserve_existing_labels: true
      
      # Super Linter Configuration
      sl_validate_all_codebase: false
      sl_enable_auto_fix: true
      sl_auto_commit_fixes: true
      
      # AI Rebase Configuration
      rebase_model: "openai/gpt-4o"
    
    secrets:
      github-token: ${{ secrets.JF_CI_GH_PAT || secrets.GITHUB_TOKEN }}

  # Optional: Notify about labeling results
  notify-results:
    needs: unified-automation
    if: always()
    runs-on: ubuntu-latest
    steps:
      - name: Report labeling results
        run: |
          echo "🤖 Intelligent Labeling Results:"
          echo "  Issues processed: ${{ needs.unified-automation.outputs.issues_processed || 'N/A' }}"
          echo "  Labels applied: ${{ needs.unified-automation.outputs.labels_applied || 'N/A' }}"
          echo "  AI fallback used: ${{ needs.unified-automation.outputs.ai_fallback_used || 'N/A' }}"
          
          if [ "${{ needs.unified-automation.result }}" = "success" ]; then
            echo "✅ Automation completed successfully"
          else
            echo "❌ Automation completed with issues"
          fi
