# file: .github/workflows/pr-labeler.yml
# version: 1.0.0
# guid: c3d4e5f6-a7b8-49c0-d1e2-f3a4b5c6d7e8

name: Pull Request Labeler

# Automatically label pull requests based on changed files and branch names
# This workflow is designed for the ghcommon, gcommon, and subtitle-manager repositories

on:
  pull_request_target:
    types: [opened, synchronize, reopened, edited]

jobs:
  labeler:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      pull-requests: write
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Apply labels to pull request
        uses: actions/labeler@v5
        with:
          repo-token: ${{ github.token }}
          configuration-path: ".github/labeler.yml"
          sync-labels: true
          dot: true
