name: Example Calling Workflow

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

# Required permissions for reusable-stale.yml
permissions:
  pull-requests: write
  issues: write

jobs:
  call-stale:
    uses: ./.github/workflows/reusable-stale.yml
    with:
      # Add required inputs here
    secrets:
      # Add required secrets here
