name: Example Calling Workflow

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

# Required permissions for reusable-intelligent-issue-labeling.yml
permissions:
  contents: read
  pull-requests: read
  issues: write

jobs:
  call-intelligent-issue-labeling:
    uses: ./.github/workflows/reusable-intelligent-issue-labeling.yml
    with:
      # Add required inputs here
    secrets:
      # Add required secrets here
