name: Example Calling Workflow

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

# Required permissions for reusable-labeler.yml
permissions:
  pull-requests: write
  contents: read
  issues: write

jobs:
  call-labeler:
    uses: ./.github/workflows/reusable-labeler.yml
    with:
      # Add required inputs here
    secrets:
      # Add required secrets here
