name: Example Calling Workflow

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

# Required permissions for reusable-unified-issue-management.yml
permissions:
  actions: write
  statuses: write
  issues: write
  checks: write
  repository-projects: write
  contents: write
  pull-requests: write
  security-events: read

jobs:
  call-unified-issue-management:
    uses: ./.github/workflows/reusable-unified-issue-management.yml
    with:
      # Add required inputs here
    secrets:
      # Add required secrets here
