name: Example Calling Workflow

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

# Required permissions for reusable-docs-update.yml
permissions:
  issues: write
  repository-projects: write
  contents: write
  pull-requests: write

jobs:
  call-docs-update:
    uses: ./.github/workflows/reusable-docs-update.yml
    with:
      # Add required inputs here
    secrets:
      # Add required secrets here
