name: Example Calling Workflow

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

# Required permissions for reusable-ci.yml
permissions:
  actions: read
  packages: write
  id-token: write
  repository-projects: write
  contents: read
  security-events: write
  attestations: write
  pull-requests: write

jobs:
  call-ci:
    uses: ./.github/workflows/reusable-ci.yml
    with:
      # Add required inputs here
    secrets:
      # Add required secrets here
