name: Example Calling Workflow

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

# Required permissions for reusable-goreleaser.yml
permissions:
  packages: write
  issues: write
  contents: write
  pull-requests: write

jobs:
  call-goreleaser:
    uses: ./.github/workflows/reusable-goreleaser.yml
    with:
      # Add required inputs here
    secrets:
      # Add required secrets here
