name: Example Calling Workflow

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

# Required permissions for reusable-semantic-versioning.yml
permissions:
  actions: read
  checks: write
  issues: write
  contents: write
  pull-requests: write

jobs:
  call-semantic-versioning:
    uses: ./.github/workflows/reusable-semantic-versioning.yml
    with: {} # Add required inputs here
    secrets: {} # Add required secrets here
