# file: .github/workflows/stale.yml
# version: 1.0.0
# guid: 336b7a2d-c53a-4ef2-927e-3bdfd733c528

name: Handle Stale Issues

on:
  schedule:
    - cron: "0 3 * * 1"
  workflow_dispatch:

# Required permissions for reusable workflows
permissions:
  contents: read
  pull-requests: write
  issues: write
jobs:
  call-stale:
    uses: jdfalk/ghcommon/.github/workflows/reusable-stale.yml@main
    with:
      days-before-stale: 90
      days-before-close: 14
    secrets:
      github-token: ${{ secrets.JF_CI_GH_PAT }}
