# file: .github/workflows/add-to-project.yml
# version: 1.0.0
# guid: b2c3d4e5-f6a7-8901-bcde-f23456789012

name: Add Issues and PRs to Projects

on:
  issues:
    types:
      - opened
      - reopened
      - labeled
  pull_request:
    types:
      - opened
      - reopened
      - labeled

permissions:
  contents: read
  issues: read
  pull-requests: read

jobs:
  # Add to ghcommon Cleanup project (primary project for this repo)
  add-to-cleanup:
    name: Add to Cleanup Project
    uses: ./.github/workflows/reusable-add-to-project.yml
    secrets:
      gh-token: ${{ secrets.JF_CI_GH_PAT }}
    with:
      project-url: "https://github.com/users/jdfalk/projects/9"
      labeled: "bug,documentation,infrastructure,cleanup"
      label-operator: "OR"

  # Add to Core Improvements project for enhancement items
  add-to-improvements:
    name: Add to Core Improvements Project
    uses: ./.github/workflows/reusable-add-to-project.yml
    secrets:
      gh-token: ${{ secrets.JF_CI_GH_PAT }}
    with:
      project-url: "https://github.com/users/jdfalk/projects/10"
      labeled: "enhancement,feature,improvement,automation"
      label-operator: "OR"

  # Add to Testing & Quality project for testing-related items
  add-to-testing:
    name: Add to Testing & Quality Project
    uses: ./.github/workflows/reusable-add-to-project.yml
    secrets:
      gh-token: ${{ secrets.JF_CI_GH_PAT }}
    with:
      project-url: "https://github.com/users/jdfalk/projects/11"
      labeled: "testing,quality,ci,workflow"
      label-operator: "OR"

  # Fallback: Add unlabeled items to cleanup project
  add-unlabeled-to-cleanup:
    name: Add Unlabeled Items to Cleanup
    if: github.event.action == 'opened' || github.event.action == 'reopened'
    uses: ./.github/workflows/reusable-add-to-project.yml
    secrets:
      gh-token: ${{ secrets.JF_CI_GH_PAT }}
    with:
      project-url: "https://github.com/users/jdfalk/projects/9"
      # No labeled filter - catches everything
