# file: .github/workflows/ci.yml
# version: 2.0.0
# guid: f1a2b3c4-d5e6-f7a8-b9c0-d1e2f3a4b5c6

name: Continuous Integration

on:
  push:
    branches: [main, master]
  pull_request:
    branches: [main, master]
  schedule:
    - cron: "0 0 * * 0" # Weekly on Sunday
  workflow_dispatch:

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  # Use the reusable CI workflow
  ci:
    name: Continuous Integration
    uses: ./.github/workflows/reusable-ci.yml
    with:
      go-version: "1.24"
      node-version: "22"
      python-version: "3.13"
      rust-version: "1.76"
      coverage-threshold: "80"
      skip-protobuf: false
      skip-tests: false
      skip-linting: false
    secrets: inherit
