# file: .github/workflows/ci.yml
# version: 1.1.0
# guid: b8c9d0e1-f2a3-44b5-c6d7-e8f9a0b1c2d3

name: CI

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]
  workflow_dispatch:

permissions:
  contents: write # Required for auto-committing linting fixes
  pull-requests: write
  actions: write # Required for uploading artifacts
  checks: write
  security-events: write
  id-token: write
  statuses: write
  # Additional permissions for dependency submission
  repository-projects: write
  packages: write
  attestations: write

jobs:
  ci:
    uses: ./.github/workflows/reusable-ci.yml
    with:
      python-version: "3.12"
      go-version: "1.22"
      run-lint: true
      run-test: true
      run-build: false
      enable-dependency-submission: true
    secrets: inherit
