# file: .github/workflows/ci.yml
# version: 1.1.0
# guid: b8c9d0e1-f2a3-44b5-c6d7-e8f9a0b1c2d3

name: CI

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]
  workflow_dispatch:

permissions:
  contents: read
jobs:
  ci:
    uses: ./.github/workflows/reusable-ci.yml
    with:
      python-version: "3.12"
      go-version: "1.22"
      run-lint: true
      run-test: true
      run-build: false
      enable-dependency-submission: true
    secrets: inherit
