# file: .github/workflows/ci-consolidated.yml
# version: 1.0.1
# guid: f1a2b3c4-d5e6-f7a8-b9c0-d1e2f3a4b5c6

name: Continuous Integration

on:
  push:
    branches: [main, master]
  pull_request:
    branches: [main, master]
  schedule:
    - cron: "0 0 * * 0" # Weekly on Sunday
  workflow_dispatch:

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

env:
  GO_VERSION: "1.24"
  NODE_VERSION: "22"
  PYTHON_VERSION: "3.12"
  COVERAGE_THRESHOLD: "80"
  CACHE_VERSION: "v1"

permissions:
  contents: write
  pull-requests: write
  issues: write
  checks: write
  statuses: write
  security-events: write
  actions: write
  packages: write
  attestations: write
  id-token: write

jobs:
  # Detect what files changed to optimize workflow execution
  detect-changes:
    name: Detect Changes
    runs-on: ubuntu-latest
    outputs:
      go: ${{ steps.filter.outputs.go }}
      frontend: ${{ steps.filter.outputs.frontend }}
      python: ${{ steps.filter.outputs.python }}
      docker: ${{ steps.filter.outputs.docker }}
      docs: ${{ steps.filter.outputs.docs }}
      workflows: ${{ steps.filter.outputs.workflows }}
      should-lint: ${{ steps.determine.outputs.should-lint }}
      should-test: ${{ steps.determine.outputs.should-test }}
      should-build: ${{ steps.determine.outputs.should-build }}
    steps:
      - name: Checkout repository
        uses: actions/checkout@v5
        with:
          fetch-depth: 0

      - name: Check file changes
        uses: dorny/paths-filter@v3
        id: filter
        with:
          filters: |
            go:
              - '**/*.go'
              - 'go.mod'
              - 'go.sum'
              - '**/go.mod'
              - '**/go.sum'
            frontend:
              - 'webui/**'
              - 'frontend/**'
              - '**/package.json'
              - '**/package-lock.json'
              - '**/yarn.lock'
              - '**/*.js'
              - '**/*.ts'
              - '**/*.jsx'
              - '**/*.tsx'
              - '**/*.vue'
              - '**/*.css'
              - '**/*.scss'
              - '**/*.sass'
              - '**/*.html'
            python:
              - '**/*.py'
              - '**/requirements.txt'
              - '**/pyproject.toml'
              - '**/setup.py'
              - '**/Pipfile'
            docker:
              - '**/Dockerfile*'
              - '**/docker-compose*.yml'
              - '**/docker-compose*.yaml'
              - '**/.dockerignore'
            docs:
              - '**/*.md'
              - '**/docs/**'
              - '**/*.rst'
            workflows:
              - '.github/workflows/**'
              - '.github/actions/**'

      - name: Determine workflow execution
        id: determine
        run: python3 .github/scripts/sync-release-build-artifacts.py
