# file: .github/workflows/manager-sync-dispatcher.yml
# version: 2.0.0
# guid: a1b2c3d4-e5f6-7890-1234-567890abcdef

name: Manager Sync Dispatcher

on:
  push:
    branches: [main]
    paths:
      - ".github/workflows/**"
      - ".github/instructions/**"
      - ".github/copilot-instructions.md"
      - "labels.json"
      - "labels.md"
  workflow_dispatch:
    inputs:
      target_repos:
        description: "Comma-separated list of repos to sync (or 'all')"
        required: false
        default: "all"
        type: string
      sync_type:
        description: "Type of sync to perform"
        required: false
        default: "all"
        type: choice
        options:
          - "all"
          - "workflows"
          - "instructions"
          - "prompts"
          - "scripts"
          - "linters"
          - "labels"

permissions:
  contents: write
  actions: write
  packages: write
  pull-requests: write
  issues: write
  repository-projects: write
  checks: write
  statuses: write
  deployments: write

env:
  # Target repositories for synchronization
  # DO NOT ADD ghcommon as that would overwrite itself.
  TARGET_REPOS: |
    jdfalk/gcommon
    jdfalk/subtitle-manager
    jdfalk/copilot-agent-util-rust
    jdfalk/apt-cacher-go
    jdfalk/audiobook-organizer

jobs:
  dispatch-sync:
    name: Dispatch Sync Events
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v5

      - name: Setup GitHub CLI
        run: |
          # GitHub CLI is pre-installed on GitHub runners
          gh --version

      - name: Determine target repositories
        id: repos
        run: ./.github/scripts/sync-determine-target-repos.sh "${{ github.event.inputs.target_repos }}" "$TARGET_REPOS"

      - name: Dispatch sync events to target repositories
        env:
          GH_TOKEN: ${{ secrets.JF_CI_GH_PAT || secrets.GITHUB_TOKEN }}
        run: ./.github/scripts/sync-dispatch-events.sh "${{ github.event.inputs.sync_type }}" "${{ steps.repos.outputs.repos }}" "${{ github.repository }}" "${{ github.sha }}"

      - name: Summary
        run: ./.github/scripts/sync-generate-summary.sh "${{ github.event.inputs.sync_type }}" "${{ steps.repos.outputs.repos }}" "${{ github.sha }}"
