# file: .github/workflows/manager-sync-dispatcher.yml
# version: 1.2.0
# guid: a1b2c3d4-e5f6-7890-1234-567890abcdef

name: Manager Sync Dispatcher

on:
  push:
    branches: [main]
    paths:
      - ".github/workflows/**"
      - ".github/instructions/**"
      - ".github/copilot-instructions.md"
      - "labels.json"
      - "labels.md"
  workflow_dispatch:
    inputs:
      target_repos:
        description: "Comma-separated list of repos to sync (or 'all')"
        required: false
        default: "all"
        type: string
      sync_type:
        description: "Type of sync to perform"
        required: false
        default: "all"
        type: choice
        options:
          - "all"
          - "workflows"
          - "instructions"
          - "prompts"
          - "scripts"
          - "linters"
          - "labels"

permissions:
  contents: read
  actions: write
  pull-requests: write

env:
  # Target repositories for synchronization
  # DO NOT ADD ghcommon as that would overwrite itself.
  TARGET_REPOS: "jdfalk/gcommon,jdfalk/subtitle-manager,jdfalk/copilot-agent-util-rust,jdfalk/apt-cacher-go,jdfalk/audiobook-organizer"

jobs:
  dispatch-sync:
    name: Dispatch Sync Events
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v5

      - name: Setup GitHub CLI
        run: |
          # GitHub CLI is pre-installed on GitHub runners
          gh --version

      - name: Determine target repositories
        id: repos
        run: |
          if [ "${{ github.event.inputs.target_repos }}" = "all" ] || [ -z "${{ github.event.inputs.target_repos }}" ]; then
            echo "repos=$TARGET_REPOS" >> $GITHUB_OUTPUT
          else
            echo "repos=${{ github.event.inputs.target_repos }}" >> $GITHUB_OUTPUT
          fi
          echo "Target repos determined: $(cat $GITHUB_OUTPUT | grep repos=)"

      - name: Debug token and permissions
        env:
          GH_TOKEN: ${{ secrets.JF_CI_GH_PAT }}
        run: |
          echo "Token check..."
          if [ -z "$GH_TOKEN" ]; then
            echo "❌ JF_CI_GH_PAT secret is not set or empty"
            exit 1
          else
            echo "✅ JF_CI_GH_PAT secret is available (length: ${#GH_TOKEN})"
          fi
          
          echo "Testing GitHub CLI authentication..."
          if gh auth status; then
            echo "✅ GitHub CLI authentication successful"
          else
            echo "❌ GitHub CLI authentication failed"
            exit 1
          fi
          
          echo "Testing repository access..."
          if gh api user; then
            echo "✅ User API access successful"
          else
            echo "❌ User API access failed"
            exit 1
          fi

      - name: Dispatch sync events to target repositories
        env:
          GH_TOKEN: ${{ secrets.JF_CI_GH_PAT }}
        run: |
          sync_type="${{ github.event.inputs.sync_type }}"
          if [ -z "$sync_type" ]; then
            sync_type="all"
          fi

          echo "Dispatching sync events for type: $sync_type"
          echo "Using token: $(if [ -n "$GH_TOKEN" ]; then echo "JF_CI_GH_PAT (length: ${#GH_TOKEN})"; else echo "NONE"; fi)"

          # Debug output
          echo "Raw repos output: ${{ steps.repos.outputs.repos }}"

          # Convert repos to array and dispatch to each
          IFS=',' read -ra REPO_ARRAY <<< "${{ steps.repos.outputs.repos }}"
          for repo in "${REPO_ARRAY[@]}"; do
            repo=$(echo "$repo" | xargs)  # trim whitespace
            if [ -n "$repo" ]; then
              echo "Dispatching to: $repo"
              if gh api repos/$repo/dispatches \
                --method POST \
                --field event_type="sync-from-ghcommon" \
                --field client_payload="{\"sync_type\":\"$sync_type\",\"source_repo\":\"${{ github.repository }}\",\"source_sha\":\"${{ github.sha }}\"}"; then
                echo "✅ Successfully dispatched to $repo"
              else
                echo "❌ Failed to dispatch to $repo"
                gh api repos/$repo/dispatches --method POST --field event_type="test" || echo "Repo access test failed"
              fi
            fi
          done

      - name: Summary
        run: |
          echo "## Sync Dispatch Summary" >> $GITHUB_STEP_SUMMARY
          echo "- **Sync Type:** ${{ github.event.inputs.sync_type || 'all' }}" >> $GITHUB_STEP_SUMMARY
          echo "- **Target Repos:** ${{ steps.repos.outputs.repos }}" >> $GITHUB_STEP_SUMMARY
          echo "- **Source SHA:** ${{ github.sha }}" >> $GITHUB_STEP_SUMMARY
