# file: .github/workflows/monitor-rollout.yml
# version: 1.0.0
# guid: 8f2d9e1a-3b4c-4f6a-9a2b-7c1d2e3f4a5b

name: Monitor Rollout

on:
  workflow_dispatch:
    inputs:
      target_repos:
        description: "Comma or space-separated list of repos (owner/name). If empty, uses .github/repositories.txt"
        required: false
  schedule:
    - cron: '17 */4 * * *' # Every 4 hours at 17 past to stagger with other jobs

permissions:
  contents: read
  actions: read

jobs:
  monitor:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Set TARGET_REPOS from input
        if: ${{ inputs.target_repos != '' }}
        run: echo "TARGET_REPOS=${{ inputs.target_repos }}" >> "$GITHUB_ENV"

      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.x'

      - name: Run monitor script
        id: monitor
        env:
          # Prefer PAT if available for cross-repo access; fall back to default token
          GITHUB_TOKEN: ${{ secrets.JF_CI_GH_PAT || secrets.GITHUB_TOKEN }}
        run: |
          python .github/scripts/monitor-rollout.py

      - name: Fail if attention needed
        if: ${{ steps.monitor.outputs.overall != 'green' }}
        run: |
          echo "Overall status: ${{ steps.monitor.outputs.overall }}; see summary above." >&2
          exit 1
