# file: .github/workflows/pr-labeler.yml
# version: 1.1.0
# guid: c3d4e5f6-a7b8-49c0-d1e2-f3a4b5c6d7e8

name: Pull Request Labeler

# Automatically label pull requests based on changed files and branch names
# Uses the reusable labeler workflow for consistency across repositories

on:
  pull_request_target:
    types: [opened, synchronize, reopened, edited]

jobs:
  labeler:
    uses: ./.github/workflows/reusable-labeler.yml
    with:
      configuration-path: ".github/labeler.yml"
      sync-labels: true
      dot: true
