# file: .github/workflows/pr-labeler.yml
# version: 1.0.0
# guid: c3d4e5f6-a7b8-49c0-d1e2-f3a4b5c6d7e8

name: Pull Request Labeler

# Automatically label pull requests based on changed files and branch names
# Uses the reusable labeler workflow from this repository

on:
  pull_request_target:
    types: [opened, synchronize, reopened, edited]

jobs:
  labeler:
    uses: jdfalk/ghcommon/.github/workflows/reusable-labeler.yml@main
    permissions:
      contents: read
      pull-requests: write
    secrets:
      github-token: ${{ secrets.JF_CI_GH_PAT }}
