# file: .github/workflows/protobuf-generation.yml
# version: 2.0.0
# guid: a1b2c3d4-e5f6-7a8b-9c0d-1e2f3a4b5c6d

name: Protocol Buffer Generation & Versioning

on:
  push:
    branches: [main, develop]
    paths:
      - "proto/**/*.proto"
      - "buf.yaml"
      - "buf.gen.yaml"
      - "scripts/post-buf-generate.py"
      - "scripts/setup-go-modules.py"
  pull_request:
    branches: [main, develop]
    paths:
      - "proto/**/*.proto"
      - "buf.yaml"
      - "buf.gen.yaml"
      - "scripts/post-buf-generate.py"
      - "scripts/setup-go-modules.py"
  workflow_dispatch:
    inputs:
      protobuf-path:
        description: "Path to protobuf source files"
        required: false
        type: string
        default: "proto"
      output-path:
        description: "Output path for generated code"
        required: false
        type: string
        default: "sdks"
      generate-docs:
        description: "Generate protobuf documentation"
        required: false
        type: boolean
        default: false
      skip-post-processing:
        description: "Skip post-generation processing scripts"
        required: false
        type: boolean
        default: false

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  protobuf-generation:
    name: Generate Protocol Buffers
    uses: ./.github/workflows/reusable-protobuf.yml
    with:
      protobuf-path: ${{ inputs.protobuf-path || 'proto' }}
      output-path: ${{ inputs.output-path || 'sdks' }}
      generate-docs: ${{ inputs.generate-docs || false }}
      skip-post-processing: ${{ inputs.skip-post-processing || false }}
    secrets: inherit