# file: .github/workflows/reusable-sync-shared-files.yml
# DEPRECATED: This workflow is now a NOOP. Use sync-to-repos.yml in ghcommon instead.
# This file remains for compatibility but does nothing and will be removed in a future release.

name: DEPRECATED - Reusable Sync Shared Files (NOOP)

on:
  workflow_call:
    inputs:
      branch:
        description: "Branch to sync from in ghcommon (default: main)"
        required: false
        default: "main"
        type: string

jobs:
  noop:
    runs-on: ubuntu-latest
    steps:
      - name: No-op
        run: |
          echo "This workflow is deprecated and does nothing. Use sync-to-repos.yml in ghcommon."
