# file: .github/workflows/reusable-add-to-project.yml
# version: 1.0.0
# guid: a1b2c3d4-e5f6-7890-abcd-ef1234567890

name: Reusable - Add to GitHub Project

on:
  workflow_call:
    inputs:
      project-url:
        description: "GitHub Project URL to add items to"
        required: true
        type: string
      labeled:
        description: "Only add items with specific labels (comma-separated)"
        required: false
        default: ""
        type: string
      label-operator:
        description: "Label matching operator (AND or OR)"
        required: false
        default: "OR"
        type: string
    secrets:
      gh-token:
        description: "GitHub Personal Access Token with project permissions"
        required: true

permissions:
  contents: read
  issues: read
  pull-requests: read

jobs:
  add-to-project:
    name: Add to Project
    runs-on: ubuntu-latest

    steps:
      - name: Validate inputs
        run: |
          if [[ -z "${{ inputs.project-url }}" ]]; then
            echo "❌ Error: project-url is required"
            exit 1
          fi

          # Validate project URL format
          if [[ ! "${{ inputs.project-url }}" =~ ^https://github\.com/(users|orgs)/[^/]+/projects/[0-9]+$ ]]; then
            echo "❌ Error: Invalid project URL format"
            echo "Expected format: https://github.com/users/USERNAME/projects/NUMBER"
            echo "                or https://github.com/orgs/ORGNAME/projects/NUMBER"
            echo "Received: ${{ inputs.project-url }}"
            exit 1
          fi

          echo "✅ Project URL validation passed: ${{ inputs.project-url }}"

      - name: Add to project
        uses: actions/add-to-project@v1.0.2
        with:
          project-url: ${{ inputs.project-url }}
          github-token: ${{ secrets.gh-token }}
          labeled: ${{ inputs.labeled }}
          label-operator: ${{ inputs.label-operator }}

      - name: Log success
        if: success()
        run: |
          echo "✅ Successfully processed item for project: ${{ inputs.project-url }}"
          if [[ -n "${{ inputs.labeled }}" ]]; then
            echo "   Labels filter: ${{ inputs.labeled }} (${{ inputs.label-operator }})"
          else
            echo "   No label filtering applied"
          fi

      - name: Log failure
        if: failure()
        run: |
          echo "❌ Failed to add item to project: ${{ inputs.project-url }}"
          echo "This could be due to:"
          echo "  - Invalid project URL"
          echo "  - Insufficient permissions on the GitHub token"
          echo "  - Project doesn't exist or isn't accessible"
          echo "  - Network connectivity issues"
