# file: .github/workflows/reusable-unified-automation.yml
# version: 2.0.0
# guid: 7a8b9c0d-1e2f-3a4b-5c6d-7e8f9a0b1c2d

name: Unified Automation Orchestrator

on:
  workflow_call:
    inputs:
      operation:
        description: "Which operation(s) to run (all, issues, docs, label, lint, rebase)"
        required: false
        default: "all"
        type: string
    secrets:
      github-token:
        description: "GitHub token with write access"
        required: true

jobs:
  issue-management:
    if: ${{ inputs.operation == 'all' || inputs.operation == 'issues' }}
    uses: ./.github/workflows/reusable-unified-issue-management.yml
    with:
      operations: auto
      dry_run: false
      force_update: false
      issue_updates_file: issue_updates.json
      issue_updates_directory: .github/issue-updates
      cleanup_issue_updates: true
      python_version: 3.11
    secrets:
      github-token: ${{ secrets.github-token }}

  docs-update:
    if: ${{ inputs.operation == 'all' || inputs.operation == 'docs' }}
    uses: ./.github/workflows/reusable-docs-update.yml
    with:
      updates-directory: .github/doc-updates
      dry_run: false
      python_version: 3.11
      cleanup_processed_files: true
      create_pr: false
      auto_merge: false
      continue_on_error: true
    secrets:
      github-token: ${{ secrets.github-token }}

  labeler:
    if: ${{ inputs.operation == 'all' || inputs.operation == 'label' }}
    uses: ./.github/workflows/reusable-labeler.yml
    with:
      configuration-path: .github/labeler.yml
      sync-labels: false
      dot: true
      pr-numbers: ""
    secrets:
      github-token: ${{ secrets.github-token }}

  super-linter:
    if: ${{ inputs.operation == 'all' || inputs.operation == 'lint' }}
    uses: ./.github/workflows/reusable-super-linter.yml
    with:
      validate-all-codebase: false
      default-branch: main
      config-file: .github/super-linter.env
      run-python: true
      run-shell: true
      run-markdown: true
      run-yaml: true
      run-json: true
      run-javascript: true
      run-go: true
      run-css: true
      run-html: true
      run-protobuf: true
      run-github-actions: true
      run-security: true
      enable-auto-fix: true
      auto-commit-fixes: true
      commit-message: "style: auto-fix linting issues [skip ci]"
    secrets:
      github-token: ${{ secrets.github-token }}

  ai-rebase:
    if: ${{ inputs.operation == 'all' || inputs.operation == 'rebase' }}
    uses: ./.github/workflows/reusable-ai-rebase.yml
    with:
      base-branch: main
      model: openai/gpt-4o
    secrets:
      github-token: ${{ secrets.github-token }}
