# file: .github/workflows/reusable-unified-automation.yml
# version: 2.7.0
# guid: 7a8b9c0d-1e2f-3a4b-5c6d-7e8f9a0b1c2d

name: Unified Automation Orchestrator

on:
  workflow_call:
    inputs:
      operation:
        description: "Which operation(s) to run (all, issues, docs, label, lint, rebase, intelligent-labeling)"
        required: false
        default: "all"
        type: string
      im_operations:
        description: "Operations for issue management workflow"
        required: false
        default: "auto"
        type: string
      im_dry_run:
        description: "Run issue management in dry-run mode"
        required: false
        default: false
        type: boolean
      im_force_update:
        description: "Force update existing issues"
        required: false
        default: false
        type: boolean
      im_issue_updates_file:
        description: "Path to legacy issue updates file"
        required: false
        default: "issue_updates.json"
        type: string
      im_issue_updates_directory:
        description: "Directory containing distributed issue updates"
        required: false
        default: ".github/issue-updates"
        type: string
      im_cleanup_issue_updates:
        description: "Cleanup processed issue update files"
        required: false
        default: true
        type: boolean
      im_python_version:
        description: "Python version for issue management"
        required: false
        default: "3.11"
        type: string

      docs_updates_directory:
        description: "Directory with documentation updates"
        required: false
        default: ".github/doc-updates"
        type: string
      docs_dry_run:
        description: "Run docs update in dry-run mode"
        required: false
        default: false
        type: boolean
      docs_python_version:
        description: "Python version for docs update"
        required: false
        default: "3.11"
        type: string
      docs_cleanup_processed_files:
        description: "Cleanup processed doc update files"
        required: false
        default: true
        type: boolean
      docs_create_pr:
        description: "Create PR for documentation changes"
        required: false
        default: false
        type: boolean
      docs_auto_merge:
        description: "Auto-merge documentation PRs"
        required: false
        default: false
        type: boolean
      docs_continue_on_error:
        description: "Continue processing even if some updates fail"
        required: false
        default: true
        type: boolean

      labeler_configuration_path:
        description: "Path to labeler configuration"
        required: false
        default: ".github/labeler.yml"
        type: string
      labeler_sync_labels:
        description: "Remove labels when files are reverted"
        required: false
        default: false
        type: boolean
      labeler_dot:
        description: "Include dot files when labeling"
        required: false
        default: true
        type: boolean
      labeler_pr_numbers:
        description: "Specific PR numbers to label"
        required: false
        default: ""
        type: string

      sl_validate_all_codebase:
        description: "Validate entire codebase with Super Linter"
        required: false
        default: false
        type: boolean
      sl_default_branch:
        description: "Default branch for Super Linter"
        required: false
        default: "main"
        type: string
      sl_config_file:
        description: "Super Linter configuration file"
        required: false
        default: ".github/super-linter.env"
        type: string
      sl_run_python:
        description: "Enable Python linting"
        required: false
        default: true
        type: boolean
      sl_run_shell:
        description: "Enable shell linting"
        required: false
        default: true
        type: boolean
      sl_run_markdown:
        description: "Enable Markdown linting"
        required: false
        default: true
        type: boolean
      sl_run_yaml:
        description: "Enable YAML linting"
        required: false
        default: true
        type: boolean
      sl_run_json:
        description: "Enable JSON linting"
        required: false
        default: true
        type: boolean
      sl_run_javascript:
        description: "Enable JavaScript linting"
        required: false
        default: true
        type: boolean
      sl_run_go:
        description: "Enable Go linting"
        required: false
        default: true
        type: boolean
      sl_run_css:
        description: "Enable CSS linting"
        required: false
        default: true
        type: boolean
      sl_run_html:
        description: "Enable HTML linting"
        required: false
        default: true
        type: boolean
      sl_run_protobuf:
        description: "Enable Protobuf linting"
        required: false
        default: true
        type: boolean
      sl_run_github_actions:
        description: "Enable GitHub Actions linting"
        required: false
        default: true
        type: boolean
      sl_run_security:
        description: "Enable security scanning"
        required: false
        default: true
        type: boolean
      sl_enable_auto_fix:
        description: "Enable auto-fixing where supported"
        required: false
        default: true
        type: boolean
      sl_auto_commit_fixes:
        description: "Automatically commit lint fixes"
        required: false
        default: true
        type: boolean
      sl_commit_message:
        description: "Commit message for lint fixes"
        required: false
        default: "style: auto-fix linting issues [skip ci]"
        type: string

      rebase_base_branch:
        description: "Branch to rebase pull requests onto"
        required: false
        default: "main"
        type: string
      rebase_model:
        description: "Model to use for AI rebase"
        required: false
        default: "openai/gpt-4o"
        type: string

      # Intelligent Issue Labeling Configuration
      il_enabled:
        description: "Enable intelligent issue labeling"
        required: false
        default: true
        type: boolean
      il_dry_run:
        description: "Run intelligent labeling in dry-run mode"
        required: false
        default: false
        type: boolean
      il_batch_size:
        description: "Number of issues to process in each batch"
        required: false
        default: 10
        type: number
      il_use_ai_fallback:
        description: "Use AI (Copilot) as fallback for complex labeling decisions"
        required: false
        default: true
        type: boolean
      il_confidence_threshold:
        description: "Minimum confidence score (0.0-1.0) required to apply labels"
        required: false
        default: 0.7
        type: number
      il_max_labels_per_issue:
        description: "Maximum number of labels to apply per issue"
        required: false
        default: 8
        type: number
      il_preserve_existing_labels:
        description: "Preserve existing labels when adding new ones"
        required: false
        default: true
        type: boolean
      il_label_config_path:
        description: "Path to intelligent labeling configuration file"
        required: false
        default: ".github/intelligent-labeling.yml"
        type: string
      il_python_version:
        description: "Python version for intelligent labeling"
        required: false
        default: "3.11"
        type: string
    secrets:
      github-token:
        description: "GitHub token for repository operations"
        required: false

jobs:
  issue-management:
    if: ${{ inputs.operation == 'all' || inputs.operation == 'issues' }}
    uses: ./.github/workflows/reusable-unified-issue-management.yml
    with:
      operations: ${{ inputs.im_operations }}
      dry_run: ${{ inputs.im_dry_run }}
      force_update: ${{ inputs.im_force_update }}
      issue_updates_file: ${{ inputs.im_issue_updates_file }}
      issue_updates_directory: ${{ inputs.im_issue_updates_directory }}
      cleanup_issue_updates: ${{ inputs.im_cleanup_issue_updates }}
      python_version: ${{ inputs.im_python_version }}
    secrets:
      github-token: ${{ secrets.GITHUB_TOKEN }}

  docs-update:
    if: ${{ inputs.operation == 'all' || inputs.operation == 'docs' }}
    uses: ./.github/workflows/reusable-docs-update.yml
    with:
      updates-directory: ${{ inputs.docs_updates_directory }}
      dry_run: ${{ inputs.docs_dry_run }}
      python_version: ${{ inputs.docs_python_version }}
      cleanup_processed_files: ${{ inputs.docs_cleanup_processed_files }}
      create_pr: ${{ inputs.docs_create_pr }}
      auto_merge: ${{ inputs.docs_auto_merge }}
      continue_on_error: ${{ inputs.docs_continue_on_error }}
    secrets: inherit

  labeler:
    if: ${{ inputs.operation == 'all' || inputs.operation == 'label' }}
    uses: ./.github/workflows/reusable-labeler.yml
    with:
      configuration-path: ${{ inputs.labeler_configuration_path }}
      sync-labels: ${{ inputs.labeler_sync_labels }}
      dot: ${{ inputs.labeler_dot }}
      pr-numbers: ${{ inputs.labeler_pr_numbers }}
    secrets: inherit

  super-linter:
    if: ${{ inputs.operation == 'all' || inputs.operation == 'lint' }}
    uses: ./.github/workflows/reusable-super-linter.yml
    with:
      validate-all-codebase: ${{ inputs.sl_validate_all_codebase }}
      default-branch: ${{ inputs.sl_default_branch }}
      config-file: ${{ inputs.sl_config_file }}
      run-python: ${{ inputs.sl_run_python }}
      run-shell: ${{ inputs.sl_run_shell }}
      run-markdown: ${{ inputs.sl_run_markdown }}
      run-yaml: ${{ inputs.sl_run_yaml }}
      run-json: ${{ inputs.sl_run_json }}
      run-javascript: ${{ inputs.sl_run_javascript }}
      run-go: ${{ inputs.sl_run_go }}
      run-css: ${{ inputs.sl_run_css }}
      run-html: ${{ inputs.sl_run_html }}
      run-protobuf: ${{ inputs.sl_run_protobuf }}
      run-github-actions: ${{ inputs.sl_run_github_actions }}
      run-security: ${{ inputs.sl_run_security }}
      enable-auto-fix: ${{ inputs.sl_enable_auto_fix }}
      auto-commit-fixes: ${{ inputs.sl_auto_commit_fixes }}
      commit-message: ${{ inputs.sl_commit_message }}
    secrets:
      github-token: ${{ secrets.GITHUB_TOKEN }}

  ai-rebase:
    if: ${{ inputs.operation == 'all' || inputs.operation == 'rebase' }}
    uses: ./.github/workflows/reusable-ai-rebase.yml
    with:
      base-branch: ${{ inputs.rebase_base_branch }}
      model: ${{ inputs.rebase_model }}
    secrets:
      github-token: ${{ secrets.GITHUB_TOKEN }}

  intelligent-labeling:
    if: ${{ inputs.operation == 'all' || inputs.operation == 'intelligent-labeling' }}
    uses: ./.github/workflows/reusable-intelligent-issue-labeling.yml
    with:
      enabled: ${{ inputs.il_enabled }}
      dry_run: ${{ inputs.il_dry_run }}
      batch_size: ${{ inputs.il_batch_size }}
      use_ai_fallback: ${{ inputs.il_use_ai_fallback }}
      confidence_threshold: ${{ inputs.il_confidence_threshold }}
      max_labels_per_issue: ${{ inputs.il_max_labels_per_issue }}
      preserve_existing_labels: ${{ inputs.il_preserve_existing_labels }}
      label_config_path: ${{ inputs.il_label_config_path }}
      python_version: ${{ inputs.il_python_version }}
    secrets: inherit
