# file: .github/workflows/sync-to-repos.yml
# version: 1.0.0
# guid: 7e2b1c4d-5f3a-4b8c-9e1f-7a6b2c3d4e5f

name: Sync Files to Other Repos

description: |
  This workflow allows maintainers to push selected files or directories from ghcommon to one or more target repositories. It can be triggered manually and supports custom repo selection.

on:
  workflow_dispatch:
    inputs:
      target_repos:
        description: 'Comma-separated list of target repos (e.g. jdfalk/subtitle-manager,jdfalk/auto-formatter)'
        required: false
        default: 'jdfalk/subtitle-manager,jdfalk/auto-formatter'
      files_to_sync:
        description: 'Comma-separated list of files or directories to sync (e.g. .github/workflows,docs)'
        required: false
        default: '.github/workflows'
      branch_name:
        description: 'Branch name to push changes to in target repos'
        required: false
        default: 'sync-from-ghcommon'

jobs:
  sync:
    name: Sync Files to Target Repos
    runs-on: ubuntu-latest
    steps:
      - name: Checkout ghcommon
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.x'

      - name: Install requirements
        run: |
          python -m pip install --upgrade pip
          pip install pyyaml

      - name: Run sync script
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          python scripts/sync_to_repos.py \
            --repos "${{ github.event.inputs.target_repos }}" \
            --files "${{ github.event.inputs.files_to_sync }}" \
            --branch "${{ github.event.inputs.branch_name }}"

      - name: Show sync summary
        if: always()
        run: |
          cat sync-summary.log || echo 'No summary generated.'
