# file: .github/workflows/sync-receiver.yml
# version: 2.0.0
# guid: f7g8h9i0-j1k2-l3m4-n5o6-p7q8r9s0t1u2

name: Sync Receiver

on:
  repository_dispatch:
    types: [sync-from-ghcommon]

permissions:
  contents: write
  pull-requests: write
  actions: write

jobs:
  sync-from-ghcommon:
    name: Sync Files from ghcommon
    runs-on: ubuntu-latest
    steps:
      - name: Checkout current repo
        uses: actions/checkout@v5
        with:
          fetch-depth: 0
          token: ${{ secrets.GITHUB_TOKEN }}

      - name: Checkout ghcommon
        uses: actions/checkout@v5
        with:
          repository: jdfalk/ghcommon
          path: ghcommon-source
          token: ${{ secrets.GITHUB_TOKEN }}

      - name: Sync files based on type
        run: ./.github/scripts/sync-receiver-sync-files.sh "${{ github.event.client_payload.sync_type }}"

      - name: Check for changes
        id: changes
        run: ./.github/scripts/sync-receiver-check-changes.sh

      - name: Commit and push changes
        if: steps.changes.outputs.has_changes == 'true'
        run: ./.github/scripts/sync-receiver-commit-push.sh "${{ github.event.client_payload.source_repo }}" "${{ github.event.client_payload.source_sha }}" "${{ github.event.client_payload.sync_type }}"

      - name: Summary
        run: ./.github/scripts/sync-receiver-generate-summary.sh "${{ github.event.client_payload.sync_type }}" "${{ github.event.client_payload.source_repo }}" "${{ github.event.client_payload.source_sha }}" "${{ steps.changes.outputs.has_changes }}"
