# file: .github/workflows/workflow-scripts-tests.yml

name: Workflow Script Tests

on:
  push:
    branches: [main]
  pull_request:
  workflow_dispatch:

jobs:
  test:
    name: Run Workflow Script Tests
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v5

      - name: Set up Python
        uses: actions/setup-python@v6
        with:
          python-version: "3.13"

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install pytest requests pyyaml "pyjwt[crypto]" cryptography

      - name: Run tests
        run: pytest tests/workflow_scripts -vv
